// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8xjKjyqKVhlFPoErTPwv9-OiUfQ2eiEM',
    appId: '1:752747962112:web:2b1c054f085cf1ad085de5',
    messagingSenderId: '752747962112',
    projectId: 'resunateproject',
    authDomain: 'resunateproject.firebaseapp.com',
    databaseURL: 'https://resunateproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resunateproject.firebasestorage.app',
    measurementId: 'G-HE8M2Y680W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpbVLE27z7B3FHVcZNf-RqrtQDdYkr9S4',
    appId: '1:752747962112:android:a4da72663696b037085de5',
    messagingSenderId: '752747962112',
    projectId: 'resunateproject',
    databaseURL: 'https://resunateproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resunateproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw9n_00-JLlFfxdgUhKtWek65DVI7YsKI',
    appId: '1:752747962112:ios:ad33dd325ac07f4d085de5',
    messagingSenderId: '752747962112',
    projectId: 'resunateproject',
    databaseURL: 'https://resunateproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resunateproject.firebasestorage.app',
    iosBundleId: 'com.example.resunateFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw9n_00-JLlFfxdgUhKtWek65DVI7YsKI',
    appId: '1:752747962112:ios:ad33dd325ac07f4d085de5',
    messagingSenderId: '752747962112',
    projectId: 'resunateproject',
    databaseURL: 'https://resunateproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resunateproject.firebasestorage.app',
    iosBundleId: 'com.example.resunateFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8xjKjyqKVhlFPoErTPwv9-OiUfQ2eiEM',
    appId: '1:752747962112:web:a29cf1fd49a6c921085de5',
    messagingSenderId: '752747962112',
    projectId: 'resunateproject',
    authDomain: 'resunateproject.firebaseapp.com',
    databaseURL: 'https://resunateproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resunateproject.firebasestorage.app',
    measurementId: 'G-47HVFZ7X29',
  );
}
